### ISSUE TITLE
Webrtc via http/https

### ISSUE THREAD

**Issue by no-1ne** [nishitm/wotop#3]
Currently Webrtc have to go thru TURN servers to achieve P2P calling on few networks,

Thanks for sharing you work, can a similar thing be used  to send then over http/https and have a js code on receiving side, convert it into UDP Webrtc data.

**Comment by no-1ne** [comment]
Wrong context I believe since it's a cpp library feel free to close issue

**Comment by nishitm** [comment]
Yea, WebRTC is a very different and mature project, serving a different purpose. Also this project is currently working with TCP data only
